"""Orthogonal lifecycle, execution, verdict, and authority vocabularies."""

from enum import StrEnum


class ImplementationStatus(StrEnum):
    SCAFFOLDED = "SCAFFOLDED"
    IMPLEMENTED_UNVALIDATED = "IMPLEMENTED_UNVALIDATED"
    PARTIALLY_VALIDATED = "PARTIALLY_VALIDATED"
    VALIDATED_FOR_SCOPE = "VALIDATED_FOR_SCOPE"
    BLOCKED = "BLOCKED"
    NOT_IMPLEMENTED = "NOT_IMPLEMENTED"


class StageRunStatus(StrEnum):
    NOT_RUN = "NOT_RUN"
    RUNNING = "RUNNING"
    WAITING_USER = "WAITING_USER"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    UNAVAILABLE = "UNAVAILABLE"
    UNSUPPORTED = "UNSUPPORTED"
    INCONCLUSIVE = "INCONCLUSIVE"
    NOT_EVALUATED = "NOT_EVALUATED"


class AssuranceVerdict(StrEnum):
    SATISFIED = "SATISFIED"
    VIOLATED = "VIOLATED"
    INCONCLUSIVE = "INCONCLUSIVE"
    UNSUPPORTED = "UNSUPPORTED"
    NOT_EVALUATED = "NOT_EVALUATED"


class AssuranceMethod(StrEnum):
    USER_CONFIRMATION = "USER_CONFIRMATION"
    DETERMINISTIC_VALIDATION = "DETERMINISTIC_VALIDATION"
    LLM_EXTRACTION = "LLM_EXTRACTION"
    REFERENCE_EXECUTION = "REFERENCE_EXECUTION"
    DIFFERENTIAL_TESTING = "DIFFERENTIAL_TESTING"
    BOUNDED_EXPLORATION = "BOUNDED_EXPLORATION"
    ADVERSARIAL_SEARCH = "ADVERSARIAL_SEARCH"
    SMT = "SMT"
    PROPERTY_CHECKING = "PROPERTY_CHECKING"
    LEDGER_VALIDATION = "LEDGER_VALIDATION"
    TESTNET_EXECUTION = "TESTNET_EXECUTION"
    DEPLOYMENT_OBSERVATION = "DEPLOYMENT_OBSERVATION"
    MANUAL_REVIEW = "MANUAL_REVIEW"


class AuthorityLevel(StrEnum):
    NO_AUTHORITY = "NO_AUTHORITY"
    MODEL_CANDIDATE = "MODEL_CANDIDATE"
    USER_ACCEPTED_INTENT = "USER_ACCEPTED_INTENT"
    DETERMINISTIC_COMPILER_CANDIDATE = "DETERMINISTIC_COMPILER_CANDIDATE"
    PROFILE_COMPILER_AUTHORITY = "PROFILE_COMPILER_AUTHORITY"
    REFERENCE_SEMANTICS_AUTHORITY = "REFERENCE_SEMANTICS_AUTHORITY"
    LEDGER_AUTHORITY = "LEDGER_AUTHORITY"


class CoverageStatus(StrEnum):
    OBSERVED = "OBSERVED"
    BOUNDED = "BOUNDED"
    COMPLETE_FOR_DEFINED_FINITE_DOMAIN = "COMPLETE_FOR_DEFINED_FINITE_DOMAIN"
