"""Controlled deterministic compiler to pinned Marlowe reference integration.

This gives differential behavioral evidence for one exact profile and reviewed
scenario. It is not general compiler proof, reviewer authentication, or ledger
validation. The Haskell executable is real; the accepted intent/review is a
synthetic integration fixture.
"""

import os
from pathlib import Path
import shutil
import subprocess

import pytest

from research.architecture.artifacts import ArtifactEnvelope
from research.architecture.ports import StageContext
from research.architecture.status import AuthorityLevel, ImplementationStatus, StageRunStatus
from research.stage2b.intent_spec import validate_intent_spec
from research.stage3.compiler import CompilerPort
from research.stage3.comparison import BehaviorExpectation, SemanticComparisonPort
from research.stage3.models import CompileResult, CompileStatus, ProfileMatchStatus
from research.stage3.profile_compilers.direct_payment_v1 import (
    DIRECT_PAYMENT_PROFILE, compile_direct_payment_v1)
from research.stage3.profiles import ProfileRegistry
from research.stage3.reference import PinnedMarloweReference, ReferenceRequest
from research.stage3.test_direct_payment_v1 import direct_payment_spec
from research.stage4.domains import ExplicitTransactionDomain, TransactionTemplate
from research.stage4.explorer import ExplorationBounds, ExplorationPort
from research.stage4.oracles import NoWarningsOracle, OraclePort


UPSTREAM_COMMIT = "7b5b1e900ec53a8eb18747992bec73470704dfcb"
REFERENCE_IDENTITY = f"{UPSTREAM_COMMIT}:0.1.0"
DRIVER_ROOT = Path(__file__).resolve().parents[2] / "tools" / "marlowe_smt"
ALICE = {"role_token": "Alice"}
BOB = {"role_token": "Bob"}
ADA = {"currency_symbol": "", "token_name": ""}
FUNDED_STATE = {"accounts": [[[ALICE, ADA], 10000000]],
                "choices": [], "boundValues": [], "minTime": 0}
FINAL_STATE = {"accounts": [], "choices": [], "boundValues": [], "minTime": 0}
NO_INPUT_TRANSACTION = {"interval": {"from": 0, "to": 0}, "inputs": []}
EXPECTED_PAYMENT = {"source_account": ALICE, "payee": {"party": BOB},
                    "token": ADA, "amount": 10000000}
EXPECTED_CONTRACT = {"pay": 10000000, "from_account": ALICE,
                     "to": {"party": BOB}, "token": ADA, "then": "close"}

# Independent scenario evidence: it is neither read from nor generated by the compiler.
REVIEWED_SCENARIO = {
    "scenario_id": "direct-payment-funded-alice-to-bob-v1",
    "reviewer_id": "compiler-reference-integration-reviewer",
    "initial_state": FUNDED_STATE,
    "transactions": [NO_INPUT_TRANSACTION],
    "expected_status": "Success",
    "expected_final_contract": "close",
    "expected_final_state": FINAL_STATE,
    "expected_warnings": [],
    "expected_payments": [EXPECTED_PAYMENT],
}


@pytest.fixture(scope="module")
def real_binary():
    if shutil.which("cabal") is None:
        pytest.skip("cabal unavailable in the Python test environment")
    if shutil.which("ghc") is None:
        pytest.skip("GHC unavailable in the Python test environment")
    resolved = subprocess.run(["cabal", "list-bin", "exe:marlowe-reference"],
                              cwd=DRIVER_ROOT, capture_output=True, text=True, check=False)
    if resolved.returncode != 0:
        pytest.fail(f"cabal list-bin failed ({resolved.returncode}): {resolved.stderr.strip()}")
    binary = resolved.stdout.strip()
    if not binary or not Path(binary).is_file():
        pytest.fail(f"missing pinned reference binary: {binary!r}")
    if not os.access(binary, os.X_OK):
        pytest.fail(f"pinned reference binary not executable: {binary}")
    return binary


def _accepted():
    spec = direct_payment_spec()
    assert validate_intent_spec(spec) == []
    return ArtifactEnvelope("accepted-intent", "v1", "integration_fixture",
                            ImplementationStatus.IMPLEMENTED_UNVALIDATED,
                            AuthorityLevel.USER_ACCEPTED_INTENT,
                            {"accepted_spec": spec, "integration_only": True})


def _compile(accepted, plugin=compile_direct_payment_v1):
    match, profile, _ = ProfileRegistry([DIRECT_PAYMENT_PROFILE]).match(
        accepted.payload["accepted_spec"])
    assert match == ProfileMatchStatus.EXACT_SUPPORTED_PROFILE
    assert profile == DIRECT_PAYMENT_PROFILE
    execution = CompilerPort(ProfileRegistry([profile]),
                             {(profile.profile_id, profile.version): plugin}).execute(
                                 [accepted], StageContext("integration-test"))
    assert execution.result.run_status == StageRunStatus.SUCCEEDED
    assert execution.result.semantic_status == CompileStatus.SUPPORTED.value
    assert execution.result.input_artifacts == [accepted.artifact_id]
    contract = next(item for item in execution.artifacts
                    if item.artifact_type == "contract-candidate")
    return contract


def _independent_expectation():
    scenario = ArtifactEnvelope("reviewed-scenario", "v1", "integration_review",
                                ImplementationStatus.IMPLEMENTED_UNVALIDATED,
                                AuthorityLevel.NO_AUTHORITY, REVIEWED_SCENARIO)
    data = scenario.payload
    expectation = BehaviorExpectation(
        scenario.artifact_id, "reviewed_scenario",
        ReferenceRequest(None, data["initial_state"], tuple(data["transactions"])),
        data["expected_status"], data["expected_final_contract"], data["reviewer_id"],
        data["expected_final_state"], tuple(data["expected_warnings"]),
        tuple(data["expected_payments"]))
    external = ArtifactEnvelope("behavior-expectation", "v1", "integration_review",
                                ImplementationStatus.IMPLEMENTED_UNVALIDATED,
                                AuthorityLevel.NO_AUTHORITY, expectation.to_dict())
    return scenario, external


def _compare(real_binary, accepted, contract, scenario, expectation):
    class IntegrationExpectationPolicy:
        def authorize(self, artifact):
            return (artifact.artifact_id == expectation.artifact_id
                    and artifact.payload["reviewer_id"] == REVIEWED_SCENARIO["reviewer_id"]
                    and artifact.payload["source_artifact_id"] == scenario.artifact_id)

    return SemanticComparisonPort(
        PinnedMarloweReference(binary=real_binary, hard_timeout_seconds=10.0),
        IntegrationExpectationPolicy()).execute(
            [accepted, contract, scenario, expectation], StageContext("integration-test"))


def test_generated_payment_matches_independent_scenario_in_real_reference(real_binary):
    accepted = _accepted()
    contract = _compile(accepted)
    assert contract.payload["contract"] == EXPECTED_CONTRACT
    scenario, expectation = _independent_expectation()
    comparison = _compare(real_binary, accepted, contract, scenario, expectation)
    assert comparison.result.run_status == StageRunStatus.SUCCEEDED
    assert comparison.result.semantic_status == "SATISFIED"
    assert comparison.result.input_artifacts == [contract.artifact_id, accepted.artifact_id,
                                                  expectation.artifact_id, scenario.artifact_id]
    payload = comparison.artifacts[0].payload
    assert payload["reference_identity"] == REFERENCE_IDENTITY
    assert "mismatches" not in payload
    raw = payload["reference_result"]
    assert raw["status"] == "Success"
    assert raw["steps"][0]["payments"] == [EXPECTED_PAYMENT]
    assert raw["steps"][0]["warnings"] == []
    assert raw["final_state"] == FINAL_STATE
    assert raw["final_contract"] == "close"

    domain = ExplicitTransactionDomain("direct-payment-real-reference-v1", [
        TransactionTemplate("NoInput", 0, 0, ())])
    exploration = ExplorationPort(
        domain, PinnedMarloweReference(binary=real_binary, hard_timeout_seconds=10.0),
        FUNDED_STATE, ExplorationBounds(max_depth=1, max_traces=1)).execute(
            [contract], StageContext("integration-test"))
    assert exploration.result.run_status == StageRunStatus.SUCCEEDED
    graph = exploration.artifacts[0].payload
    assert graph["coverage"] == "BOUNDED"
    assert len(graph["traces"]) == 1
    trace = graph["traces"][0]
    assert trace["status"] == "Success"
    assert trace["steps"][0]["meta"] == {"upstream_commit": UPSTREAM_COMMIT,
                                          "reference_driver_version": "0.1.0"}
    assert trace["steps"][0]["steps"][0]["payments"] == [EXPECTED_PAYMENT]
    assert trace["steps"][0]["steps"][0]["warnings"] == []
    oracle = OraclePort([NoWarningsOracle()]).execute(
        exploration.artifacts, StageContext("integration-test"))
    assert oracle.artifacts[0].payload["findings"][0]["verdict"] == "SATISFIED"


def test_wrong_close_contract_passes_structure_but_fails_payment_comparison(real_binary):
    accepted = _accepted()

    def wrong_compiler(ir):
        correct = compile_direct_payment_v1(ir)
        assert correct.status == CompileStatus.SUPPORTED
        return CompileResult(CompileStatus.SUPPORTED, "close", correct.mapping_evidence)

    wrong_contract = _compile(accepted, wrong_compiler)
    assert wrong_contract.payload["contract"] == "close"
    scenario, expectation = _independent_expectation()
    comparison = _compare(real_binary, accepted, wrong_contract, scenario, expectation)
    assert comparison.result.run_status == StageRunStatus.FAILED
    assert comparison.result.semantic_status == "VIOLATED"
    payload = comparison.artifacts[0].payload
    assert payload["reference_identity"] == REFERENCE_IDENTITY
    assert payload["mismatches"] == ["payments"]
    raw = payload["reference_result"]
    assert raw["status"] == "Success" and raw["final_contract"] == "close"
    assert raw["final_state"] == FINAL_STATE and raw["steps"][0]["warnings"] == []
    assert raw["steps"][0]["payments"] == [{
        "source_account": ALICE, "payee": {"party": ALICE},
        "token": ADA, "amount": 10000000}]
