cabal-version: 3.4
name: marlowe-smt
version: 0.2.0.0
build-type: Simple

executable marlowe-smt
  main-is: Main.hs
  hs-source-dirs:
    app
    src
    upstream/marlowe/haskell/src
  other-modules:
    MarloweSMT.Analysis
    MarloweSMT.Bridge
    MarloweSMT.Output
    Language.Marlowe.Pretty
    Language.Marlowe.Deserialisation
    Language.Marlowe.Semantics
    Language.Marlowe.Semantics.Deserialisation
    Language.Marlowe.Semantics.Types
    Language.Marlowe.Analysis.FSSemanticsFastVerbose
  build-depends:
    base >=4.18 && <5,
    aeson >=2.2 && <2.3,
    base16-bytestring ==1.0.2.0,
    bytestring >=0.11 && <0.13,
    containers >=0.6 && <0.7,
    cryptohash ==0.11.9,
    process >=1.6 && <1.7,
    sbv ==10.12,
    text >=2.1 && <2.2,
    vector ==0.13.2.0,
    wl-pprint ==1.2.1
  default-language: Haskell2010
  default-extensions:
    AllowAmbiguousTypes
    BlockArguments
    ConstraintKinds
    DataKinds
    DefaultSignatures
    DeriveAnyClass
    DeriveDataTypeable
    DeriveFoldable
    DeriveFunctor
    DeriveGeneric
    DeriveLift
    DeriveTraversable
    DerivingStrategies
    DerivingVia
    DuplicateRecordFields
    EmptyCase
    EmptyDataDeriving
    ExplicitForAll
    FlexibleContexts
    FlexibleInstances
    FunctionalDependencies
    GADTs
    GeneralizedNewtypeDeriving
    ImportQualifiedPost
    LambdaCase
    MultiWayIf
    NamedFieldPuns
    NumericUnderscores
    OverloadedRecordDot
    OverloadedStrings
    PatternSynonyms
    PolyKinds
    RankNTypes
    RecordWildCards
    ScopedTypeVariables
    StandaloneDeriving
    TupleSections
    TypeApplications
    TypeFamilies
    TypeOperators
    UndecidableInstances
    ViewPatterns

executable marlowe-reference
  main-is: ReferenceMain.hs
  hs-source-dirs:
    app
    src
    upstream/marlowe/haskell/src
  other-modules:
    MarloweSMT.Bridge
    MarloweSMT.Output
    Language.Marlowe.Pretty
    Language.Marlowe.Deserialisation
    Language.Marlowe.Semantics
    Language.Marlowe.Semantics.Deserialisation
    Language.Marlowe.Semantics.Types
  build-depends:
    base >=4.18 && <5,
    aeson >=2.2 && <2.3,
    base16-bytestring ==1.0.2.0,
    bytestring >=0.11 && <0.13,
    containers >=0.6 && <0.7,
    cryptohash ==0.11.9,
    process >=1.6 && <1.7,
    sbv ==10.12,
    text >=2.1 && <2.2,
    vector ==0.13.2.0,
    wl-pprint ==1.2.1
  default-language: Haskell2010
  default-extensions:
    DeriveAnyClass
    DeriveGeneric
    DerivingStrategies
    GeneralizedNewtypeDeriving
    LambdaCase
    OverloadedStrings
    ScopedTypeVariables
